- GMAO_ods/CMakeLists.txt
- GMAO_pyobs/CMakeLists.txt
> fixes f2py race condition

- GEOS_Util/coupled_diagnostics/analysis/clim/plot_aice_clim.py
- GEOS_Util/coupled_diagnostics/analysis/clim/plot_extent_anncycle.py
- GEOS_Util/coupled_diagnostics/analysis/clim/plot_hice_icesat.py
- GEOS_Util/coupled_diagnostics/analysis/clim/plot_mean_vel_anncycle.py
- GEOS_Util/coupled_diagnostics/analysis/clim/plot_volume_anncycle.py
Updates for sea ice plots in coupled diagnostics.
> Update to sea ice plots

- GEOS_Util/plots/fcst/pltcorcmpz.gs
- GEOS_Util/plots/fcst/pltrmscmpz.gs
- GEOS_Util/plots/grads_util/cor.gs
- GEOS_Util/plots/grads_util/corave.gs
- GEOS_Util/plots/grads_util/corcmp_plot.gs
- GEOS_Util/plots/grads_util/corcmpz.gs
- GEOS_Util/plots/grads_util/corcmpz_plot.gs
- GEOS_Util/plots/grads_util/corz.gs
- GEOS_Util/plots/grads_util/rms.gs
- GEOS_Util/plots/grads_util/rmscmp_plot.gs
- GEOS_Util/plots/grads_util/rmscmpz.gs
- GEOS_Util/plots/grads_util/rmscmpz_plot.gs
- GEOS_Util/plots/grads_util/rmsz.gs
- GEOS_Util/plots/grads_util/tcor.gs
These are the latest plot scripts from `Jason-3_2` on CVS
> Update to latest plot scripts from CVS

- .github/CODEOWNERS
Make sure @lltakacs needs to approve things in `post` and `plots`.
Make sure @yvikhlya needs to approve changes in `coupled_diagnostics`.
> Fixes #29. Update CODEOWNERS

- CMakeLists.txt
Sort of trivial, but only tested in FV standalone mode.  Needs a 2nd
set of eyes.
> Fixes #33.

- GMAO_etc/Remote_utils.pm
> Update Remote_utils.pm to fix issue #45

- GEOS_Util/post/CMakeLists.txt
- LANL_Shared/LANL_cice/drivers/cice4/ice_prescribed_mod.F90
This is simply the `stats.x` endian fix.
> Pull master into dev/MAPL-2.0

- GEOS_Util/post/regrid.pl
Some suggestions for @gmao-jstassi.
- Clearer names for WEmin in/out (though `weminin` looks a little awkward. Perhaps `wemin_in` for the option name?)
- Provide info about WEmin before prompt, so the average person doesn't have to think long about if they have the right choice.
> clearer WEmin variables names and info

- GEOS_Util/post/regrid.pl
Fixes to regrid.pl working agian
1. Make wem arguments match what mk_restarts expects in latest version
2. A few updates from so this can work on sles12
3. Minor fixes because the ability to run this interactively was broken as it was trying to copy a log file which was the slurm log from the catch regridding job which is not there if you are running interactively.
> regrid.pl bug fixes

- GEOS_Util/plots/fcst/pltcorcmpz.gs
- GEOS_Util/plots/fcst/pltrmscmpz.gs
- GEOS_Util/plots/grads_util/corcmpz_plot.gs
- GEOS_Util/plots/grads_util/gencmpz.gs
- GEOS_Util/plots/grads_util/rmscmpz_plot.gs
- GEOS_Util/post/ecmwf2geos.pl
- GEOS_Util/post/g5fcst_stats.pl
- GEOS_Util/post/ncep2geos.pl
Enhancements to GF and transport consistent with ops 525land_fpp. Must be taken in conjunction with pull requests in [GEOSgcm_GridComp#190](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/190), [GEOSgcm_App#84](https://github.com/GEOS-ESM/GEOSgcm_App/pull/84), and [GEOSchem_GridComp#47](https://github.com/GEOS-ESM/GEOSchem_GridComp/pull/47).
> Updates from f525land_fpp/Jason-3_4 tags and Plot Updates

- GEOS_Util/post/gcmplot.script
- GEOS_Util/post/gcmpost.script
- GEOS_Util/post/gcmpost_CPLFCSTfull.script
- GEOS_Util/post/gcmpost_CPLFCSTpart.script
Works in concert with GEOS-ESM/GEOSgcm_App#97
> Use sbatch at NCCS, qsub at NAS

- GEOS_Util/post/gcmpost.script
Modified gcmpost.script to only operate on pressure-level collections
> J36p2_updates

- GEOS_Util/post/gcmpost.script
> reference to time_ave.rc changed from $GEOSUTIL/bin to $GEOSUTIL/post

- LANL_Shared/LANL_cice/source/ice_grid.F90
For some reason, Intel really wasn't happy with opening a file everywhere.
> Fixes to allow Intel 19.1.2 to use CICE

- .circleci/config.yml
Adds a CircleCI build test to GEOS_Shared.
> Add CircleCI build for GEOS_Shared

- .github/CODEOWNERS
- .github/workflows/changelog-enforcer.yml
- CHANGELOG.md
> Update the changelog to present day

- CHANGELOG.md
- GEOS_Util/post/gcmclim.script
- GEOS_Util/post/gcmpost.script
- GEOS_Util/post/gcmpost_CPLFCSTfull.script
- GEOS_Util/post/gcmpost_CPLFCSTpart.script
This is an attempt to SLURM-ify some code in `gcmpost.script`, `gcmclim.script`, et al. I'm not quite sure how to best test it, so I'll put a blocker on this until @sdrabenh or @lltakacs can try it out.
> Fixes #128. Refactor PBS_NODEFILE code in post

- .circleci/config.yml
- CHANGELOG.md
Updates CI image to match the latest ESMA_env
> Update CI to 6.0.22

- .circleci/config.yml
This PR updates the CircleCI to use the `large` resource due to resumption of paid plan.
> Update CircleCI to use large

- CHANGELOG.md
- GMAO_psas/m_GetAI.F90
- GMAO_psas/m_psas.F90
Ben,
Please find the two files that change on this. I know you have similar changes, still ...
Ricardo
> get it work w/ MAPL2; this still needs a real fix

- GMAO_hermes/m_dyn_util.F90
Add ability to write out energy fields to file.
> add ability to write out energy components to file

- CHANGELOG.md
- GMAO_hermes/CMakeLists.txt
- GMAO_hermes/echorc.pl
> Adding new script echorc.pl to @GMAO_Shared/GMAO_hermes

- GMAO_etc/obsys-nccs.rc
- GMAO_hermes/dyn2dyn.f90
- GMAO_hermes/m_dyn_util.F90
Changes to allow DAS to run w/ increased number of levels.
> minor fix; 181 levs; freq

- CHANGELOG.md
- GMAO_etc/CMakeLists.txt
- GMAO_etc/pyrob_CF
I was informed by @keknowland that there is a `pyrob_CF` script that the GEOS-CF folks use. This adds it here so we capture it on GitHub
> Add pyrob_CF script

- CHANGELOG.md
- GMAO_ods/conv-kx.readme
- GMAO_ods/kx_register.tbl
- GMAO_ods/ozone-kx.readme
- GMAO_ods/radiance-kx.readme
This is a duplicate of #167 but to the `main` branch rather than to the `release/cvs/GEOSadas-5_27_1_p2` branch.
#167 is too far away from `main` for git to handle cleanly.
> Updates to documentation tables for KX values (main branch)

- CHANGELOG.md
- GMAO_etc/pyrob
This PR adds support to `pyrob` to support the proposed/new GEOS-IT files.
> Add support for GEOS-IT in pyrob

- CHANGELOG.md
- GMAO_etc/idcheck.pl
This update will allow fvsetup to check whether the expid already exists in the SemperPy databases. This feature was working previously before changes in SemperPy caused it to no longer work.
> The idcheck.pl script was updated for changes in SemperPy

- .circleci/config.yml
- CHANGELOG.md
In working toward #241, first let's move GMAO_Shared to use CircleCI Orbs.
> Use circleci-tools orb for CI

- CHANGELOG.md
- GEOS_Util/post/regrid.pl
This is a pretty minor PR. Just adds a few tags to `regrid.pl` and then fixed up the changelog to reflect the released versions.
> Update tags in regrid.pl. Fix up changelog

- GEOS_Util/post/remap_restart/remap_params.py
- GEOS_Util/post/remap_restart/remap_questions.py
- GEOS_Util/post/remap_restart/remap_restarts.py
This PR re-orders the questions to match regrid.pl
> re-order questions 

- CHANGELOG.md
- GEOS_Util/post/remap_restart/remap_catchANDcn.py
EASE grid tile file name does not contain pfafxxx
> update EASE grid tile file name

- CHANGELOG.md
- GMAO_etc/obsys-nccs-gaas-geosit.rc
- GMAO_etc/obsys-nccs-gaas-r21c.rc
- GMAO_etc/obsys-nccs-geosit.rc
- GMAO_etc/obsys-nccs-r21c.rc
- GMAO_ods/kx_register.tbl
- GMAO_ods/ods_dcget.f
- GMAO_ods/odsmeta.h
- GMAO_ods/ozone-kx.readme
Labeled as zero-diff from the GCM perspective. Updates originally from @elakkraoui
> Proposed R21C changes 2024-01-29

- CHANGELOG.md
- GMAO_etc/Remote_utils.pm
This is an update needed by the OPS group.
> Patch FP: per request from OPS group

- CHANGELOG.md
- GMAO_etc/obsys-nccs.rc
This brings in capability (class) for OMPS-LP in FP - per K. Wargan's implementation/testing. Zero-diff when class not present.
> FP Patch: add class for OMPS-LP

- CHANGELOG.md
- CMakeLists.txt
Simple fix up the changelog for a 1.9.9 release.
> Update changelog for 1.9.9 release

- CHANGELOG.md
- GMAO_ods/CMakeLists.txt
- GMAO_ods/pyods/__init__.py
These are needed to get the AOD analysis to work. These have been brought up from 5.41.1
> Needed for AOD analysis to work properly

- .github/workflows/spack-ci.yml
- .github/workflows/workflow.yml
- CHANGELOG.md
This PR adds CI from Github Actions until CircleCI can come back online
> Add Github Actions CI

- GMAO_etc/cmpdir.pl
* corrected left/right brace error with perl on SLES-15
* use cmp command to compare files if cdo command fails
* add nc4 files to list of files excluded with the -binX flag
* pause instead of immediately showing menu after displaying diff text differences
> Updates to cmpdir.pl script:

- .circleci/config.yml
- .editorconfig
- .github/workflows/workflow.yml
- CHANGELOG.md
- GMAO_gfio/CMakeLists.txt
This PR fixes an issue with unprotected f2py code.
Also: fix up the CI.
> v12: Fix issue with unprotected f2py code
