GEOS-ESM/GMAO_Shared

- GMAO_etc/CMakeLists.txt
Technically, only one (`lats4d`) is an actual script, but they are all
executable in CVS
> Install the grads scripts as executables

- GMAO_ods/CMakeLists.txt
Per @gmao-msienkie, `GMAO_ods` should be built with big endian conversion
> Fixes #21. GMAO_ods needs big endian

- CMakeLists.txt
Turns out CMake `EXISTS` requires a full path.
Also, remove Chem_Base and Chem_Shared. They are in a different repo. :smile:
> Fixes #35. Fix GMAO_gfio existence check

- GEOS_Shared/CMakeLists.txt
- GEOS_Shared/getco2.F90
This is to let both `GEOSldas` and `GEOSgcm` see this file
> Fixes #38. Add getco2.F90 to GEOS_Shared

- GEOS_Util/post/CMakeLists.txt
This matches how `stats.F90` was built in CVS. In truth, it might be better to later (after testing) make it work as little-endian
> Fixes #49. Build stats.x as big-endian

- GEOS_Util/plots/CMakeLists.txt
- GEOS_Util/plots/quickstat
Use `configure_file()` to correct set the installation directory in `quickstat`
> Fixes #53. Git fixes for quickstat

- GMAO_etc/esma_mpirun
`esma_mpirun` does a check if you are running Intel MPI on SLURM and puts in a protection for running with `-perhost`. A test shows this isn't needed with Intel MPI on SLES 12.
> Fixes #88. Intel MPI on SLES 12/SLURM 19 is good

- LANL_Shared/LANL_cice/source/ice_read_write.F90
This is part of merges from CVS S2S3 tag into git and includes update to CICE, which allows both ifort and gfortran to read CICE grid file. Previous version has problem with gfortran, since it has different default record length than ifort. @zhaobin74 could you please review this again?
> This update to CICE allows reading binary grid files with both ifort and

- GEOS_Shared/lightning_toolbox_mod.F90
If one compiles `lightning_toolbox_mod.F90` with OpenMP on, it will fail due to an extraneous comma. I don't know if it *works* with OpenMP on (as GEOS doesn't build that way) but it will at least build.
> Fixes #104. Remove extraneous comma

- GMAO_hermes/CMakeLists.txt
- GMAO_transf/CMakeLists.txt
Thanks to @nosolls, there were two places in GMAO_Shared that failed to build with GCC 10 when using Release flags because of idiosyncratic CMake. The solution is to add `${MISMATCH}` to the CMake. Note that on Intel this is a *blank* flag, thus nothing should change make-wise.
> Fixes GCC 10 Release Build

- GMAO_transf/CMakeLists.txt
Use this r4i4 version of ncesp_sp in gmao_transf. This is needed so that the GEOSgcm.x will link to this version allowing the JCAP functionality to work again in mkiau gridcomp as that needs the r4 version. Note this is non-zero diff if using stochastic phyiscs (SPPT: 1 and SKEP: 1). However, I would be suspicious of any answer from that as if you turn on that option with debugging it fails in the stochastic physics with an out of bounds error.
> Use r4i4 ncep_sp in gmao_transf

- GMAO_etc/esma_mpirun
For some reason (perhaps because I built Open MPI 4.0.4 incorrectly, though I didn't change anything from my 4.0.3 builds), using:
```
mpirun -bind-to core -map-by core
```
with Open MPI 4.0.4 and Intel 19.1.1 fails. It just crashes. But, since Open MPI isn't a "performance" stack, perhaps defaulting to "just" `mpirun` is a good default, and it seems to work.
Weirdly, the more complex:
```
mpirun -bind-to core -map-by ppr:N:node
```
*does* work. Weird.
> Edit Open MPI flags

- GMAO_etc/esma_mpirun
On CI systems, AWS, and other non-NASA or GMAO-maintained systems, the usual MPI stack is Open MPI. `esma_mpirun` will fail if it doesn't find any of the environmental variables that are often set on NCCS/NASA/GMAO machines through modulefiles.
To that end, set the default `mpi_type` to `openmpi` so it will at least default to that if nothing is found.
> Assume Open MPI as a default mpi stack

- GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMakeLists.txt
- GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/README_lake
- GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/gen_input.csh
- GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/lake_data_EIGTHdeg.F90
- GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/plot_bcs.py
- GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/proc_singleDay.csh
- GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/read_bin.f90
This PR adds code to generate:
1. A mask (=0. or 1.), its value =1 over **Great Lakes and Caspian Sea**. 
2. SST and Ice concentration for any day from either OSTIA SST (binned from its native 1/20 deg to 1/8deg; see below for grid information). If OSTIA SST has no data, we extract from Reynolds SST (and Ice conc) after converting it from its native 1/4 deg to 1/8. All of the grid conversions and extraction of data from Reynolds (if needed) is same as what is currently done for processing SST and Ice Conc data in proc_SST_FRACI.F90
**Note:** The grid is global lat/lon, dlat = dlon = 1/8 deg; dateline edge, pole edge, i.e., starting lat = -90 +  dlat/2, similarly for starting lon. 
In addition it adds:
- Scripts to generate the data (gen_input.csh, proc_singleDay.csh); see README_lake …
> Feature/san akel/for data lake

- CHANGELOG.md
- GEOS_Shared/CMakeLists.txt
- GEOS_Shared/atmOceanIntLayer.F90
This PR:
resolves https://github.com/GEOS-ESM/GMAO_Shared/issues/116
All the subroutines that are called from within `OPENWATERCORE` of `GEOS_OpenWaterGridComp.F90` have been moved here so they can be _shared_ across: applications and components.
For what it is worth, it is a zero-diff change: AMIP and Coupled.
> Feature/san akel/simplify aoil

- CHANGELOG.md
- GEOS_Shared/GEOS_Utilities.F90
The `GEOSadas-5_27_0` version of this file has slightly different code, `nint()` instead of `int()`. This brings us inline. 
Marking as non-zero-diff as it might be.
> Update GEOS_Utilities to match ADAS

- CHANGELOG.md
- GEOS_Shared/GEOS_Utilities.F90
Using `nint()` instead of `int()` in `GEOS_Utilities.F90` can cause crashes if Debugging flags are on. To wit we look at this code:
```fortran
real,    parameter :: TMINTBL    =  150.0
real,    parameter :: TMAXTBL    =  333.0
integer, parameter :: DEGSUBS    =  100
...
integer, parameter :: TABLESIZE  =  nint(TMAXTBL-TMINTBL)*DEGSUBS + 1
...
real,    save      :: ESTBLX(TABLESIZE)
```
`TABLESIZE` evaluates to (333-150)*100+1 = 18301
Now we look at
```fortran
if    (TL<=TMINTBL) then
TI = TMINTBL
elseif(TL>=TMAXTBL-.001) then
TI = TMAXTBL-.001
else
TI = TL
end if
TI = (TI - TMINTBL)*DEGSUBS+1
IT = nint(TI)
if(URAMP==TMIX) then
DQ    = ESTBLX(IT+1) - ESTBLX(IT)
QSAT  = (TI-IT)*DQ + ESTBLX(IT)
else
DQ    = ESTBLE(IT+1) - ESTBLE(IT)
QSAT  = (TI-IT)*DQ + ESTBLE(IT)
endif
```
So let's say `TL` …
> Move back to using int() not nint(): Bug in Table Evaluation

- .circleci/config.yml
- CHANGELOG.md
Per Docker, soon there will be [limits on unauthenticated pulls](https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/). CircleCI recommends using contexts to authenticate. This PR adds the authentication
> Add Docker authentication for pulls

- GEOS_Shared/GEOS_Utilities.F90
This PR is to add logger calls (at a WARNING level) for the QSAT and DQSAT codes. Recently, a case was found where a NaN was passed down into GEOS_QSAT and this led to a crash. With these loggers, the user would at least get a warning that a NaN was passed before the model inevitably crashes.
Example output is:
```
QSAT: WARNING:  QSAT0: TL contains NaN
```
Also, runs were made with and without this code to determine if the `ieee_is_nan()` call was expensive or not. The results are below with Throughput (days/day): 
| Resolution | Stock | IEEE |
| - | - | - |
| c48 | 569.414  | 562.533 |
| c90 | 216.222  | 219.643 |
| c180 | 126.599  | 128.268 |
| c360 | 112.156  | 113.598 |
| c720 | 44.752 | 45.567 |
As can be seen there is little cost to the calls at least on the order of discover …
> Add logger for NaN detection in QSAT calls

- CHANGELOG.md
- GEOS_Util/plots/CMakeLists.txt
- GEOS_Util/plots/configure
One issue with running someone else's experiment is that if you do plots, you eventually need to set up links that are done with `plots/configure`. But someone else can't run `configure` in your build. 
This commit will do that. I had to do a few things like *hardcode* `GEOSUTIL` because...well...it has to be. We need the right `GEOSUTIL` so the links are in the right place!
> Edits to make plots/configure portable

- .github/workflows/changelog-enforcer.yml
- CHANGELOG.md
- GEOS_Util/coupled_diagnostics/CMakeLists.txt
- GEOS_Util/plots/CMakeLists.txt
- GEOS_Util/post/CMakeLists.txt
- GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMakeLists.txt
- GMAO_etc/CMakeLists.txt
- GMAO_hermes/CMakeLists.txt
When a `GLOB` is used in CMake, the CMake system doesn't check to see if files in the `GLOB` change when re-running `cmake`. Thus if someone adds/removes a file that the `GLOB` would pick up, say, CMake might not see there is a change and things go a bit pear-shaped. But there is [a `CONFIGURE_DEPENDS` flag](https://cmake.org/cmake/help/latest/command/file.html#glob):
> If the CONFIGURE_DEPENDS flag is specified, CMake will add logic to the main build system check target to rerun the flagged GLOB commands at build time. If any of the outputs change, CMake will regenerate the build system.
While CMake prefers no `GLOB` at all (as `CONFIGURE_DEPENDS` isn't supported for all generators), for now this is a possible partial solution until the CMake could be rewritten to explicitly list all …
> Use CONFIGURE_DEPENDS with GLOB

- CHANGELOG.md
- GEOS_Util/plots/CMakeLists.txt
- GEOS_Util/plots/res/zonal.gs
Per @lltakacs it was found that `zonal.f` was being compiled differently in git than in CVS. This seemed to be causing issues. This is a PR to update the CMake. Note that @lltakacs says there seem to still be issues beyond this. But this is a placeholder for now until he or @sdrabenh can figure it out.
> Update flags for zonal.f to match CVS; fix zonal.gs

- CHANGELOG.md
- GEOS_Util/post/regrid.pl
This PR adds a `-partition` option to `regrid.pl`.
Note that this PR is dependent on https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/392 as we need to pass the `-partition` down to `mk_restarts`
> Add partition option for regrid

- CHANGELOG.md
- GEOS_Shared/Lightning_mod.F90
This is a bug fix for the following issue: https://github.com/GEOS-ESM/GMAO_Shared/issues/99
Arrays ple and cnvMfc are now referenced using the indices LM:0 (instead of LM+1:1):
```
pleHemco(:,:,1:KM) = ple(:,:,LM:0:-1)
cnvMfcHemco(:,:,1:KM) = cnvMfc(:,:,LM:0:-1)
```
Similarly, the index was shifted by -1 for array geoPotHeight so that it now spans the valid range:
```
do levCount=1,LM
gridBoxHeightHemco(:,:,levCount) = geoPotHeight(:,:,levCount-1) - geoPotHeight(:,:,levCount)
enddo
```
> Bug fix for issue #99: Edge level arrays out-of-bounds in Lighting_mod

- CHANGELOG.md
- GEOS_Util/post/binarytile.F90
This PR is contingent on this PR in MAPL:
https://github.com/GEOS-ESM/MAPL/pull/725
This PR is needed for eventual implementation of the river routing model. The river model will require modification to the tile files to include the number of pfafstetter catchments on the first line as the 2nd number. Right now binarytile.x was copying one number from the first line (number of tiles) to the binary. This will copy two if they exist. Note that this should not break anything as no one has ever previously cared about the other numbers that may be there which is the raster size used to create the file. Sarith said no utility uses this information.
> Update binarytile.x for river routing

- CHANGELOG.md
For some reason, the CHANGELOG was not updated quite right for recent releases. This gets it back on track
> Fix CHANGELOG for recent releases

- CHANGELOG.md
- GEOS_Pert/GEOS_PertShared/CMakeLists.txt
- GEOS_Pert/GEOS_PertSvecs/CMakeLists.txt
- arpack/SRC/CMakeLists.txt
When trying to build the DAS with the latest GMAO_Shared they do not sparse out arpack and the cmake command was failing. This fixes it.
> Fixed CMake bugs for DAS build only libraries

- CHANGELOG.md
- GEOS_Util/post/regrid.pl
This is a `main` line update to `regrid.pl` to mirror that from @gmao-jstassi in #174. Per #174:
> Fixed the -wemin and -wemout options so that they will accept integer values; Also added Jason-NL BCS tag choice
> Update main regrid.pl a la #174

- CHANGELOG.md
- GEOS_Shared/Lightning_mod.F90
This PR accompanies [PR #430 in GEOSgcm_GridComp](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/430). It prevents a seg-fault when calculating the lightning flash rate implemented in HEMCO/GEOS-Chem. Instead of explicitly assuming the lower and upper bound indeces of the array on model edges, it uses LBOUND and UBOUND instead. This seems to be necessary to prevent an out-of-bounds error in arrays `ple`, `cnvMfc`, and `geoPotHeight`.
This PR is zero-diff and fixes a problem that only showed up when requesting diagnostics `LFR_GCC` in combination with a replay simulation.
> Zero-diff bug fix preventing out-of-bounds error when calculating GEOS-Chem lightning flash rate

- GEOS_Util/post/CMakeLists.txt
- GEOS_Util/pre/NSIDC-OSTIA_SST-ICE_blend/CMakeLists.txt
This is some CMake changes mainly to prevent `.mod` files from being in the `build/src` directory tree. 
Most of GEOS will put its `.mod` files in a `build/include` directory based on the library being made. So, for example, the `.mod` files for Moist are in `build/include/GEOSmoist_GridComp/`. And the GEOS CMake framework handles this 99% of the time. But in a few places, we find `.mod` files not yet in the `build/include` tree. This fixes those.
This is one of those "If it builds, it's zero-diff" PRs since the only changes are to the build and not to any source codes.
> Fixes some CMake Fortran_MODULE_DIRECTORY

- CHANGELOG.md
- GMAO_etc/esma_mpirun
These are updates for (re-)enabling MVAPICH2 with GEOS.  This changes the command `esma_mpirun` uses for MVAPICH2.
Should be taken in concert with https://github.com/GEOS-ESM/GEOSgcm_App/pull/239 (not *required*, just for best performance)
> Updates for MVAPICH2

- .github/workflows/changelog-enforcer.yml
- CHANGELOG.md
This is an update to the changelog enforcer that now allows a more exciting error message. Unfortunately, the error is only on the Details of the check, but now it's *nice and explicit*!
Also, remove the ability for 0-diff trivial PRs to skip. Too many PRs are labeled as trivial when they aren't!
> Update changelog enforcer

- GEOS_Util/post/regrid.pl
1) This regrid.pl depends on some mk_restart programs in GEOSgcm_GridComp. This is not desirable and needs further discussion to re-organize the codes. 
2) @gmao-jkolassa,  I don't know perl and don't know how to use regrid.pl but I made changes anyway.  So I really need help to test the program with this branch https://github.com/GEOS-ESM/GEOSgcm_GridComp/tree/feature/wjiang/jkolassa_cnclm45_mk_restart . I believe what we need for the command line is the CN_VERSION to be "clm40" or clm45"
> change the CN_VERSION and restart name

- CHANGELOG.md
- LANL_Shared/CICE4/CMakeLists.txt
This is a fix for a run-time segfault for CICE4. This needs ESMA_cmake v3.6.1 due to needing a new CMake variable.
> Fix for CICE4 segfault

- CHANGELOG.md
- GEOS_Util/post/regrid.pl
Closes #94 
This updates the flags in `regrid.pl` which were quite old.
> Closes #94. Update mpi variables in regrid

- .circleci/config.yml
- CHANGELOG.md
This PR updates the CI to use Baselibs 6.2.8. This is futureproofing for MAPL development which needs a newer version of gFTL that doesn't affect GEOS as a whole yet.
This is still zero-diff for GEOS.
> Update CI to Baselibs 6.2.8

- .circleci/config.yml
- CHANGELOG.md
This PR compresses the CircleCI artifacts since CircleCI will soon charge for storage over a limit:
https://circleci.com/docs/2.0/persist-data/#storage
This is trivially zero-diff to the model as it only affects CI
> Compress CircleCI Artifacts

- CHANGELOG.md
I noticed that the changelog didn't have the 1.5.1 release. This fixes that up.
> Fix up changelog for 1.5.1

- CHANGELOG.md
- GEOS_Util/post/CMakeLists.txt
This PR just puts the module file from `3CH.F90` into the `include/` directory. Minor tweak, but it makes Ninja happier and keeps the build dir clean.
> Minor CMake change for mod file

- CHANGELOG.md
- GEOS_Util/post/gcmclim.script
- GEOS_Util/post/gcmpost.script
Change the default output of most collections to use MAPL's monthly mean and compression. Turn off automatic archiving to mass storage. Changes enable compatibility with plots package.
> Use the monthly attribute by default

- CHANGELOG.md
- GMAO_ncdiag/nc_diag_cat/CMakeLists.txt
- GMAO_ncdiag/nc_diag_read/CMakeLists.txt
- GMAO_ncdiag/nc_diag_write/CMakeLists.txt
- GMAO_ods/CMakeLists.txt
This PR updates the CMake in some ADAS-only subdirs a la #254. 
Note that this technically requires ESMA_cmake v3.15.1 (https://github.com/GEOS-ESM/GEOSgcm/pull/418) though GEOSgcm builds will never notice that.
> Update CMake in ADAS-only subdirs

- .circleci/config.yml
- CHANGELOG.md
- GEOS_Util/post/regrid.pl
> geocachem ==> achem name changed

- CHANGELOG.md
- GEOS_Util/post/gcmpost.script
Implemented a more robust check to test if a history's monthly attribute is 1 (on) and not commented out.
> Robust check for history's monthly attribute

- .github/workflows/changelog-enforcer.yml
- .github/workflows/validate_yaml_files.yml
- .yamllint.yml
- CHANGELOG.md
- GEOS_Util/post/remap_restart/remap_params.tpl
- GEOS_Util/post/remap_restart/remap_utils.py
- GEOS_Util/post/tests/c180Toc360.yaml
- GEOS_Util/post/tests/c24Toc12.yaml
- GEOS_Util/post/tests/c360Toc24.yaml
- GEOS_Util/post/tests/f522Toc360.yaml
- GEOS_Util/post/tests/s2sToc12MOM6.yaml
- GEOS_Util/post/tests/s2sv3Toc12MOM6.yaml
- GEOS_Util/post/tests/test_remap_cases.yaml
This PR adds an S2Sv3-MOM5 to C12-MOM6 test case to the remapping tests. It also has some fixes from @weiyuan-jiang while debugging other issues I found/created. 😄 
It also adds a YAML validator and cleans up the existing YAML files to pass.
> Add S2Sv3 to MOM6 test. Add YAML validator

- CHANGELOG.md
- GMAO_etc/CMakeLists.txt
- GMAO_perllib/CMakeLists.txt
Testing with @rtodling found that the GMAO_Shared CMake doesn't know that GMAO_etc depends on Perl modules in GMAO_perllib, e.g., `GMAO_etc/Manipulate_time.pm` depends on `GMAO_perllib/Time/JulianDay.pm`.
So we add some dummy CMake targets so that we can express this dependency.
> Make GMAO_etc depend on GMAO_perllib

- GEOS_Util/post/regrid.pl
`Regrid.pl` can't be used with new boundary conditions `v09` that contain snow albedo information. 
This PR is to let users know that regrid.pl  is in process of being phased out and replaced with remap_restarts.py.  We need this for [PR#618 on GEOSgcm_GridComp](https://github.com/GEOS-ESM/GEOSgcm_GridComp/pull/618))
> add warning message for users 

- CHANGELOG.md
- GEOS_Util/post/regrid.pl
- GEOS_Util/post/remap_restart/remap_utils.py
Closes #302 
This PR fixes an issue in `regrid.pl` and `remap_restarts.py` when remapping from MERRA-2 from 2021-06 to 2021-09. 
The fix is a bit hacky...but the code was a bit hacky. I think it works, but I'll mention @weiyuan-jiang so he can more carefully test the remapping script.
> Fixes #302. Fix regrid/remap for MERRA-2

- .circleci/config.yml
- CHANGELOG.md
This PR is needed to support updates in MAPL and GEOSgcm_App.
> Update CircleCI to Baselibs 7.7.0

- CHANGELOG.md
- GEOS_Util/post/remap_restart/remap_questions.py
- GEOS_Util/post/remap_restart/remap_utils.py
In using `remap_restarts.py` I found a bug in the handling of MERRA2. This fixes it to be consistent with `regrid.pl`
Also, set the default data ocean for C90+ to be `CS` as that is usually what people use.
> Fix issue with MERRA2 remapping

- CHANGELOG.md
- GEOS_Util/post/remap_restart/remap_questions.py
Since Haswell nodes are being decomissioned.
> Get rid of `hasw` in remap_restart utility

- .circleci/config.yml
- CHANGELOG.md
This is an attempt to fix up the CI for PRs to the GEOS-IT branch.
Fixing version of GEOSgcm to a branch `GEOS-IT-for-CI` which is based on the GEOSadas `GEOS-IT` branch.
Also, turning off the `mepodevelop` stage as that will cause issues.
> Fixes for GEOS-IT CI

- CHANGELOG.md
- GMAO_etc/WriteLog.pm
Tests of `regrid.pl` on SLES15 by @sdrabenh found that Perl 5.26 acts differently. He got:
```
Unescaped left brace in regex is illegal here in regex; marked by <-- HERE in m/(\${ <-- HERE (\w+)})/ at /gpfsm/dnb78s1/projects/p18/sdrabenh/Models/KM_v11.3.2/install-SLES15/bin/WriteLog.pm line 627.
```
Searches online show that in Perl 5.26 [literal braces must be escaped](https://perldoc.perl.org/5.26.0/perldelta#Unescaped-literal-%22%7B%22-characters-in-regular-expression-patterns-are-no-longer-permissible)
Tests will be needed to make sure this doesn't break runs of `regrid.pl` on SLES12
> Fixes for perl 5.26 on SLES15

- CHANGELOG.md
- LANL_Shared/CICE4/bld/makdep.c
Building GEOS with GCC 14 found an issue where `makdep.c` did not declare `main` as an `int`. GCC 14 no longer allows implicit int main it seems.
> gcc14: Add int to main in makdep.c

- CHANGELOG.md
- GEOS_Shared/CMakeLists.txt
- GMAO_stoch/CMakeLists.txt
This PR updates the ESMF CMake target to `ESMF::ESMF` which is the correct canonical target name for ESMF. This is necessary for Spack compatibility. NOTE: This requires ESMF 8.6.1 or later.
> Update ESMF CMake target to ESMF::ESMF

- CHANGELOG.md
- GMAO_etc/obsys-nccs-r21c.rc
Instead of expecting the user to have to know that something needs to be filled in in obsys.rc to handle the internally generated prepbufr (and corresponding aircraft file) this generalizes it so that the FVHOME and EXPID get filled in on the fly by the DAS scripts.
> General handling of GMAO-preqc files

- .github/workflows/changelog-enforcer.yml
- .github/workflows/validate_yaml_files.yml
Soon, GitHub will deprecate the upload-artifacts v3 action. This PR updates the action to the latest version, v4.
It also updates the checkout action to the latest version, v4, as well.
> Update GitHub Actions

- CHANGELOG.md
- GMAO_etc/esma_mpirun
Testing with MVAPICH 4 on discover found we need to always bind to cores with GEOS. This automates it.
> Updates for MVAPICH 4

- .editorconfig
- CHANGELOG.md
- GMAO_gfio/CMakeLists.txt
Testing with GEOSfvdycore on Spack revealed an issue with f2py. Namely, the GFIO f2py code in CMake did not respect `-DUSE_F2PY:BOOL=OFF`. This PR fixes that.
I also add an `.editorconfig` file because I saw this didn't have it.
> Fix issue with unprotected f2py code

- CHANGELOG.md
- CMakeLists.txt
Closes #386 
If the `gmao2ioda` directory doesn't exist, we can't `INSTALL` it. So, we check if it exists.
> Fixes #386. Only install gmao2ioda if it exists

- CHANGELOG.md
- GMAO_etc/esma_mpirun
This PR updates how `esma_mpirun` is run with openmpi. It will run with `-map-by node -bind-to core`
Keeping draft until I fully test.
> Update openmpi in esma_mpirun
